# Generated by Django 5.1.2 on 2024-10-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_data', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('delivery_city', models.CharField(max_length=150)),
                ('delivery_address', models.CharField(max_length=250)),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('delivery_time', models.TimeField(auto_now_add=True)),
                ('package_type', models.CharField(choices=[(None, 'Выберите тип пакета'), ('letter', 'Письмо'), ('parcel', 'Бандероль'), ('bulky cargo', 'Крупногабаритный груз')])),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ['-load_data'],
            },
        ),
    ]
