# Generated by Django 5.1.2 on 2024-10-25 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatusCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, choices=[(None, 'Выберите статус'), ('New', 'Новая'), ('Done', 'Завершенная'), ('Cancelled', 'Закрытая'), ('Handed to courier', 'Передано курьеру'), ('In process', 'В процессе')], null=True)),
                ('load_data', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='my_app.delivery')),
            ],
            options={
                'verbose_name': 'Статус доставки',
                'verbose_name_plural': 'Статусы доставки',
                'ordering': ['-load_data'],
            },
        ),
    ]
