# Generated by Django 5.1.2 on 2024-11-05 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_deliverystatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystatuscurrent',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.delivery'),
        ),
        migrations.AlterField(
            model_name='deliverystatushistory',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.delivery'),
        ),
    ]
