# Generated by Django 5.1.2 on 2024-11-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='city',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Город'),
        ),
    ]
