# Generated by Django 5.1.2 on 2024-12-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_warehouse_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_city',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='package_type',
            field=models.CharField(choices=[(None, 'Выберите тип пакета'), ('letter', 'Письмо'), ('parcel', 'Бандероль'), ('bulky cargo', 'Крупногабаритный груз')], default=None),
        ),
        migrations.AlterField(
            model_name='deliverystatuscurrent',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='my_app.delivery'),
        ),
    ]
